# Generated by Django 3.2.18 on 2023-06-12 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=30, verbose_name='Sede')),
                ('direccion', models.CharField(max_length=35, verbose_name='Dirección')),
                ('referente', models.CharField(max_length=15, verbose_name='Referente')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Comisión')),
                ('comision', models.CharField(max_length=15, verbose_name='Comisión')),
                ('status', models.CharField(choices=[('Activa', 'Activa'), ('Reagrupada', 'Reagrupada'), ('Cerrada', 'Cerrada'), ('Egresada', 'Egresada')], max_length=10)),
                ('campus', models.ForeignKey(on_delete=models.SET('Sede Eliminada'), to='fines.campus')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Persona')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('', 'Seleccione su género'), ('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=30, verbose_name='Género')),
                ('nacionalidad', models.CharField(blank=True, choices=[('', 'Seleccione su nacionalidad'), ('Argentina', 'Argentina'), ('Boliviana', 'Boliviana'), ('Brasileña', 'Brasileña'), ('Chilena', 'Chilena'), ('Colombiana', 'Colombiana'), ('Ecuatoriana', 'Ecuatoriana'), ('Paraguaya', 'Paraguaya'), ('Peruana', 'Peruana'), ('Uruguaya', 'Uruguaya'), ('Venezolana', 'Venezolana'), ('Otro', 'Otro')], max_length=55, verbose_name='Nacionalidad')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('celular_1', models.IntegerField(verbose_name='Celular')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha inscripción')),
                ('domicilio', models.CharField(blank=True, max_length=100, verbose_name='Domicilio')),
                ('barrio', models.CharField(blank=True, choices=[('', '---'), ('Avellaneda', 'Avellaneda'), ('Caraza', 'Caraza'), ('C.A.B.A', 'C.A.B.A'), ('Gerli', 'Gerli'), ('Fiorito', 'Fiorito'), ('Lanús Este', 'Lanús Este'), ('Lanús Oeste', 'Lanús Oeste'), ('Lomas de Zamora', 'Lomas de Zamora'), ('Valentín Alsina', 'Valentín Alsina'), ('V. Jardín', 'V. Jardín'), ('V. Diamante', 'V. Diamante')], max_length=55, verbose_name='Localidad/Barrio')),
                ('celular_2', models.CharField(blank=True, max_length=10, verbose_name='Celular 2')),
                ('estudios', models.CharField(blank=True, choices=[('', 'Seleccione maximo nivel alcanzado'), ('primaria completa', 'Primaria 6to o 7mo grado completo'), ('1ro / 6 años', '1ro secundaria común de 6 años o Técnica de 7 años'), ('2do / 6 años', '2do secundaria común de 6 años o Técnica de 7 años'), ('3ro / 6 años', '3ro secundaria común de 6 años o Técnica de 7 años'), ('4to / 6 años', '4to secundaria común de 6 años o Técnica de 7 años'), ('5to / 6 años', '5to secundaria común de 6 años o Técnica de 7 años'), ('6to / 6 años', '6to secundaria común de 6 años o Técnica de 7 años'), ('1ro comun o técnica', '1ro secundaria común de 5 años o Técnica de 6 años'), ('2do comun o técnica', '2do secundaria común de 5 años o Técnica de 6 años'), ('3ro comun o técnica', '3ro secundaria común de 5 años o Técnica de 6 años'), ('4to comun o técnica', '4to secundaria común de 5 años o Técnica de 6 años'), ('5to comun o técnica', '5to secundaria común de 5 años o Técnica de 6 años'), ('7mo', '7mo año EGB'), ('8vo', '8vo año EGB'), ('9no', '9no año EGB'), ('9no Adultos', '9no año/3er ciclo EGB Adultos'), ('1ro polimodal', '1ro polimodal'), ('2do polimodal', '2do polimodal'), ('3ro polimodal', '3ro polimodal'), ('1ro ESB', '1ro secundaria básica ESB'), ('2do ESB', '2do secundaria básica ESB'), ('3ro ESB', '3ro secundaria básica ESB'), ('1ro fines', '1ro de Plan Fines o CENS'), ('2do fines', '2do de Plan Fines o CENS'), ('3ro fines', '3ro de Plan Fines o CENS'), ('1ro BAOT/BAO', '1ro de BAOT/BAO'), ('2do BAOT/BAO', '2do de BAOT/BAO'), ('3ro BAOT/BAO', '3ro de BAOT/BAO'), ('Otro', 'Otro')], max_length=255, verbose_name='Estudios previos')),
                ('otros_estudios', models.CharField(blank=True, max_length=255, verbose_name='Otros estudios')),
                ('materias_adeudadas', models.TextField(blank=True, verbose_name='Materias Adeudadas')),
                ('colegio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colegio')),
                ('pais', models.CharField(blank=True, max_length=50, verbose_name='País del colegio')),
                ('provincia', models.CharField(blank=True, max_length=50, verbose_name='Provincia del colegio')),
                ('localidad', models.CharField(blank=True, max_length=50, verbose_name='Ciudad del colegio')),
                ('turno_manana', models.BooleanField(default=False, verbose_name='Turno mañana')),
                ('turno_tarde', models.BooleanField(default=False, verbose_name='Turno tarde')),
                ('turno_noche', models.BooleanField(default=False, verbose_name='Turno noche')),
                ('sede', models.CharField(blank=True, max_length=55, verbose_name='Sede de preferencia')),
                ('ex_alumno', models.BooleanField(default=False, verbose_name='Ex Alumno')),
                ('comision', models.ManyToManyField(to='fines.Comision')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id_orientacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Orientación')),
                ('orientacion', models.CharField(max_length=40, verbose_name='Orientación')),
                ('resolucion', models.CharField(max_length=10, verbose_name='N° Resolución')),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Orientación',
                'verbose_name_plural': 'Orientaciones',
            },
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.IntegerField(verbose_name='Libro')),
                ('folio', models.IntegerField(verbose_name='Folio')),
                ('dni_copia', models.BooleanField(verbose_name='DNI Copia')),
                ('p_nac_copia', models.BooleanField(verbose_name='P. Nac. Copia')),
                ('certificado', models.BooleanField(verbose_name='Certificado de estudios')),
                ('constancia', models.BooleanField(verbose_name='Constancia')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.estudiante', verbose_name='Estudiante')),
                ('orientacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.orientacion', verbose_name='Orientación')),
            ],
            options={
                'verbose_name': 'Legajo',
                'verbose_name_plural': 'Legajos',
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='orientacion',
            field=models.ForeignKey(on_delete=models.SET('Orientación Eliminada'), to='fines.orientacion'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Asignatura')),
                ('asignatura', models.CharField(max_length=40, verbose_name='Asignatura')),
                ('horas', models.IntegerField(verbose_name='Horas Cátedra')),
                ('cuatrimestre', models.CharField(max_length=4, verbose_name='Cuatrimestre')),
                ('baja', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='fines.estudiante')),
                ('orientacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.orientacion', verbose_name='Orientación')),
            ],
            options={
                'verbose_name': 'Materias',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
