# Generated by Django 3.2.18 on 2023-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='barrio',
            field=models.CharField(max_length=55, verbose_name='Localidad/Barrio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(max_length=255, null=True, verbose_name='Colegio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estudios',
            field=models.CharField(max_length=255, null=True, verbose_name='Estudios previos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='localidad',
            field=models.CharField(max_length=50, null=True, verbose_name='Ciudad del colegio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=55, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='otros_estudios',
            field=models.CharField(max_length=255, null=True, verbose_name='Otros estudios'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais',
            field=models.CharField(max_length=50, null=True, verbose_name='País del colegio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='provincia',
            field=models.CharField(max_length=50, null=True, verbose_name='Provincia del colegio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sede',
            field=models.CharField(max_length=55, null=True, verbose_name='Sede de preferencia'),
        ),
    ]
