# Generated by Django 3.2.18 on 2023-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='genero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=55, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='genero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=55, verbose_name='Nacionalidad'),
        ),
    ]
